services:
  - type: web
    name: auto-appraisal-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:fastapi_app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon
